In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

import missingno as mns
import warnings
warnings.filterwarnings('ignore')

In [5]:
# Load the data
data = pd.read_csv('../Data/covid19indiaorg/raw_data24.csv')

In [6]:
# Make a copy of the data
rd_df = data.copy()

In [7]:
rd_df.head()

,Entry_ID,State Patient Number,Date Announced,Age Bracket,Gender,Detected City,Detected District,Detected State,State code,Num Cases,Current Status,Contracted from which Patient (Suspected),Notes,Source_1,Source_2,Source_3,Nationality,Type of transmission,Status Change Date,Patient Number
0,503873,NaN,28/02/2021,NaN,NaN,NaN,Adilabad,Telangana,TG,6,Hospitalized,NaN,NaN,https://twitter.com/IPRTelangana/status/136587...,NaN,NaN,NaN,NaN,NaN,NaN
1,503874,NaN,28/02/2021,NaN,NaN,NaN,Bhadradri Kothagudem,Telangana,TG,5,Hospitalized,NaN,NaN,https://twitter.com/IPRTelangana/status/136587...,NaN,NaN,NaN,NaN,NaN,NaN
2,503875,NaN,28/02/2021,NaN,NaN,NaN,Hyderabad,Telangana,TG,27,Hospitalized,NaN,NaN,https://twitter.com/IPRTelangana/status/136587...,NaN,NaN,NaN,NaN,NaN,NaN
3,503876,NaN,28/02/2021,NaN,NaN,NaN,Jagtial,Telangana,TG,9,Hospitalized,NaN,NaN,https://twitter.com/IPRTelangana/status/136587...,NaN,NaN,NaN,NaN,NaN,NaN
4,503877,NaN,28/02/2021,NaN,NaN,NaN,Jangaon,Telangana,TG,2,Hospitalized,NaN,NaN,https://twitter.com/IPRTelangana/status/136587...,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
rd_df.shape

(3456, 20)

In [10]:
rd_df.isnull().sum()

Entry_ID                                        0
State Patient Number                         3456
Date Announced                                  0
Age Bracket                                  3393
Gender                                       3393
Detected City                                3456
Detected District                              43
Detected State                                  0
State code                                      0
Num Cases                                       0
Current Status                                  0
Contracted from which Patient (Suspected)    3456
Notes                                        3455
Source_1                                      131
Source_2                                     3266
Source_3                                     3456
Nationality                                  3456
Type of transmission                         3456
Status Change Date                           3456
Patient Number                               3456
dtype: int64